### ISSUE TITLE
update overhead/efficiency

### ISSUE THREAD

**Issue by casperdcl** [tmux-plugins/tmux-cpu#27]
Things like `nvidia-smi` can take some time to run (up to a few seconds) so we should try to call them only once per update. Right now, using e.g. `#{gpu_icon} #{gpu_percentage}` will call `nvidia-smi` twice.

Fixing this will also help with #5

**Comment by casperdcl** [comment]
also @ctjhoa considering #22 #27 #28 #29 and [`git fame -wtMC --excl='\.png$'`](https://github.com/casperdcl/git-fame) I'm responsible for about 1/4 of this repo (LoC) or 1/3 (files) - would be nice to be added as a collaborator/team member :)

**Comment by ctjhoa** [comment]
@casperdcl 
> would be nice to be added as a collaborator/team member :)

Sure, that's what I had in mind. Unfortunately, I don't think I'm able to do that myself. As this plugin is part of the `tmux-plugins` organization, only the organization's owner is able to add new collaborators.

@bruno- can you add @casperdcl as collaborator of this project, please? Thanks

**Comment by ctjhoa** [comment]
Since github upgrade I've managed to invite you as collaborator. Another information not directly related but with 0e6fb34a3ec499c6239e8bb3c4867e3449588a09 I have added customization on the format used to display percentage. So I've change the default gpu_percentage_format to `%3.1f%%` (formerly `%3.0%%`) which add one decimal, this was needed to get the same behavior between cpu and gpu. Thanks
